---
- name: "Ansible Create directory if not exists"
  file:
     path: "{{ mysql_bak_path }}"
     state: directory
    #  mode: 0755
    #  group: root
    #  owner: root
  # when: db_folder.stat.exists == false

- name: MySQL | Backup site DB
  mysql_db:
    name: "{{ mysql_uat_db }}"
    login_host: "localhost"
    login_user: "root"
    login_password: "{{ mysql_root_pass }}"
    login_unix_socket: /data/db/mysql/mysql.sock
    target: "{{ mysql_bak }}"
    state: dump
  become: yes
  # ignore_errors: true1
